#!/usr/bin/env python

class Hostname(object):

	def __init__(self, module):
		self.name = module.params['name']
		self.file = '/etc/hostname'
		self.err = None

	def set(self, name):
		try:
			file = open(self.file, 'w')
			file.write(self.name)
			file.close()
		except IOError as e:
			self.err = 'Cannot open {}'.format(self.file)
			return False
		return True

def main():

	module = AnsibleModule(
		argument_spec = dict(
			name = dict(required=True),
		)
	)

	host = Hostname(module)

	if host.set(host.name):
		module.exit_json(changed=True)

	module.fail_json(name=host.name, msg=host.err)


from ansible.module_utils.basic import *
main()
